# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0043_courserun_course_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_metadata.FAQ'),
        ),
    ]
